name: 'Setup smalltalkCI'
description: 'Set up smalltalkCI for testing Squeak/Smalltalk, Pharo, GemStone,
  and Moose projects'
author: 'Software Architecture Group, Hasso Plattner Institute'
inputs:
  smalltalk-version:
    description: 'Smalltalk image selection (see smalltalkCI''s list of
      supported images)'
    required: true
  smalltalkCI-source:
    description: 'Smalltalk CI source repo'
    required: false
    default: 'https://github.com/hpi-swa/smalltalkCI'
  smalltalkCI-branch:
    description: 'Branch or tag to use from Smalltalk CI repo'
    required: false
    default: 'master'
outputs:
  smalltalk-version:
    description: 'Smalltalk image selection'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'box'
  color: 'blue'
